---
apiVersion: v1  
kind: Service  
metadata:  
  name: ${MYAPP_NAME}-service-name  
  namespace: ${MYAPP_NAME}-namespace  
  annotations:  
   service.kubernetes.io/topology-mode: auto  
spec:  
  selector:  
    app: demo  
  ports:  
    - protocol: TCP  
      port: 80  
      targetPort: 8080
